# Generated by Django 3.1.12 on 2025-03-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrolled_on',
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('ARI', 'Artificial Intelligence'), ('CSE', 'Computer Science')], default='CSE', max_length=3),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='123456', max_length=255),
        ),
    ]
